import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import styles from '../styles/Home.module.css'

export default function Home() {

  const chave = "123";
  const [loading, setLoading] = useState(false);
  const [access, setAccess] = useState(false);
  const [porcoes, setPorcoes] = useState(0);
  const [ultimaPorcao, setUltimaPorcao] = useState("");

  const registerUser = (event: any) => {
    event.preventDefault()
    setLoading(true);
    //get chave
    setTimeout(() => {
      setLoading(false)
      if (event.target.name.value == chave) {
        setAccess(true);
      } else {
        alert("Chave de validação incorreta.");
      }
    }, 1000);
  }

  const alimentar = () => {
    setLoading(true);
    setTimeout(() => {
      alert("A ração foi liberada!");
      setPorcoes(porcoes + 1);
      setUltimaPorcao(novaData());
      setLoading(false);
    }, 1000)
  }

  function novaData() {
    var date = new Date().getDate();
    var month = new Date().getMonth() + 1;
    var year = new Date().getFullYear();
    var hours = new Date().getHours();
    var min = new Date().getMinutes();
    var sec = new Date().getSeconds();
    return (
      date + '/' + month + '/' + year
      + '  -  ' + hours + ':' + min + ':' + sec
    );
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Hungry Dog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/dog.png" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet" />
      </Head>

      <main className={styles.main}>
        <Image
          src="/assets/dog.png"
          alt="Picture of the author"
          width={150}
          height={150}
        />
        <h1 className={styles.title}>
          Hungry Dog
        </h1>
        {!loading ?
          access ?
            <div className={styles.buttonFeed}>
              {porcoes != 1 ?
                <span>{porcoes} Porções</span>
                :
                <span>{porcoes} Porção</span>}
              <button onClick={alimentar} className={`${styles.btn} ${styles.effect01}`}><span>alimentar</span></button>
              <span>Ultima dose {ultimaPorcao}</span>
            </div>
            :
            <form onSubmit={registerUser} className={styles.form}>
              <label htmlFor="name">Informe a chave de validação</label>
              <div className={styles.inputDiv}>
                <input id="name" type="text" autoComplete="name" required className={styles.field} />
                <button className={`${styles.btn} ${styles.effect01}`} type="submit"><span>validar</span></button>
              </div>
            </form>
          :
          <div className={styles.gooey}>
            <span className={styles.dot}></span>
            <div className={styles.dots}>
              <span></span>
              <span></span>
              <span></span>
            </div>
          </div>
        }
      </main>
      <footer className={styles.footer}>
        <a
          href="http://ifmt.edu.br/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made for {' '}
          <span className={styles.logo}>
            <Image src="/assets/ifmt.svg" alt="Ifmt Logo" width={100} height={100} />
          </span>
        </a>
      </footer>
    </div>
  )
}
