import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import styles from '../styles/Home.module.css'
import { ler, darRacao, validar } from '../src/service/alimentar';

export default function Home() {

  const [loading, setLoading] = useState(false);
  const [chave, setChave] = useState("");
  const [access, setAccess] = useState(false);
  const [porcoes, setPorcoes] = useState(0);
  const [ultimaPorcao, setUltimaPorcao] = useState("");

  const validarChave = async (event: any) => {
    setChave(event.target.name.value);
    event.preventDefault()
    setLoading(true);
    try {
      const resp = await validar("Payam Hungry", event.target.name.value);
      if (resp.data.success) {
        setPorcoes(resp.data.totalPorcoes);
        setUltimaPorcao(resp.data.ultimaPorcao);
        setAccess(true);
      } else {
        alert("Chave de validação incorreta.");
      }
    } catch (e) {
      alert(e);
    }
    setLoading(false);
  }

  const alimentar = async () => {
    setLoading(true);
    const leitura = await ler();
    if (leitura.data.status == "PEDINDO") {
      alert("Aguarde, o Hungry Dog está em andamento!");
    } else {
      const respRacao = await darRacao("Payam Hungry", chave);
      if (respRacao.data.success) {
        setPorcoes(respRacao.data.totalPorcoes);
        setUltimaPorcao(respRacao.data.ultimaPorcao);
        alert("A solicitação foi enviada!");
      } else {
        alert("A solicitação falhou.");
      }
    }
    setLoading(false);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Hungry Dog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/dog.png" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet" />
      </Head>

      <main className={styles.main}>
        <Image
          src="/assets/dog.png"
          alt="Picture of the author"
          width={150}
          height={150}
        />
        <h1 className={styles.title}>
          Hungry Dog
        </h1>
        {!loading ?
          access ?
            <div className={styles.buttonFeed}>
              {porcoes != 1 ?
                <span>{porcoes} Porções</span>
                :
                <span>{porcoes} Porção</span>}
              <button onClick={alimentar} className={`${styles.btn} ${styles.effect01}`}><span>alimentar</span></button>
              <span>Última porção {ultimaPorcao}</span>
            </div>
            :
            <form onSubmit={validarChave} className={styles.form}>
              <label htmlFor="name">Informe a chave de validação</label>
              <div className={styles.inputDiv}>
                <input id="name" type="password" required className={styles.field} />
                <button className={`${styles.btn} ${styles.effect01}`} type="submit"><span>validar</span></button>
              </div>
            </form>
          :
          <div className={styles.gooey}>
            <span className={styles.dot}></span>
            <div className={styles.dots}>
              <span></span>
              <span></span>
              <span></span>
            </div>
          </div>
        }
      </main>
      <footer className={styles.footer}>
        <div>
          <p>Trabalho de Conclusão de Curso</p>
          <p>Payam Kaffashi</p>
          <p>payamkaffashi@hotmail.com</p>
        </div>
        <a
          href="https://www.ufmt.br/"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>
            <Image src="/assets/ufmt.jpg" alt="Ufmt Logo" width={84} height={98} />
          </span>
        </a>
      </footer>
    </div>
  )
}
